"use client";
import { useEffect,useState,type FormEvent } from "react";
import { api,context } from "./provider-app";
import { clinicCreatedDoctorError,platformStatus,type ClinicCreatedDoctor } from "./clinic-created-doctors";

type Draft={displayName:string;email:string;mobileNumber:string;dateOfBirth:string;sex:ClinicCreatedDoctor["sex"];specialization:string};
const empty:Draft={displayName:"",email:"",mobileNumber:"",dateOfBirth:"",sex:"NOT_SPECIFIED",specialization:""};

export function ClinicCreatedDoctorsPanel(){
  const [items,setItems]=useState<ClinicCreatedDoctor[]|null>(null);const [open,setOpen]=useState(false);const [draft,setDraft]=useState<Draft>(empty);const [error,setError]=useState<string>();const [notice,setNotice]=useState<string>();const [busy,setBusy]=useState(false);const [clinicId,setClinicId]=useState<string>();
  async function load(){const value=await context();const clinic=value.clinics[0];if(!clinic)return {clinicId:undefined,items:[] as ClinicCreatedDoctor[]};return {clinicId:clinic.id,items:(await api<{items:ClinicCreatedDoctor[]}>(`/v1/me/clinics/${encodeURIComponent(clinic.id)}/created-doctors`)).items};}
  useEffect(()=>{let current=true;void load().then(value=>{if(current){setClinicId(value.clinicId);setItems(value.items);}}).catch(cause=>{if(current)setError(clinicCreatedDoctorError(cause));});return()=>{current=false;};},[]);
  function update<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(current=>({...current,[key]:value}));}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!clinicId)return;setBusy(true);setError(undefined);setNotice(undefined);try{const response=await api<{doctor:ClinicCreatedDoctor}>(`/v1/me/clinics/${encodeURIComponent(clinicId)}/created-doctors`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});setItems(current=>[response.doctor,...(current??[])]);setDraft(empty);setOpen(false);setNotice("Doctor created and sent for Platform approval.");}catch(cause){setError(clinicCreatedDoctorError(cause));}finally{setBusy(false);}}
  return <section className="panel"><div className="section-header"><div><p className="eyebrow">Clinic team</p><h2>Clinic-created doctors</h2><p className="muted">Create a doctor for Platform review. Approval does not replace professional verification.</p></div><button disabled={busy||!clinicId} onClick={()=>setOpen(value=>!value)} type="button">{open?"Close form":"Create Doctor"}</button></div>{open?<form onSubmit={(event)=>void submit(event)}><div className="field-grid"><label>Full Name<input autoComplete="name" disabled={busy} onChange={event=>update("displayName",event.target.value)} required value={draft.displayName}/></label><label>Email<input autoComplete="email" disabled={busy} onChange={event=>update("email",event.target.value)} required type="email" value={draft.email}/></label><label>Mobile Number<input autoComplete="tel" disabled={busy} onChange={event=>update("mobileNumber",event.target.value)} placeholder="+919999999999" required type="tel" value={draft.mobileNumber}/></label><label>Date of Birth<input disabled={busy} max={new Date().toISOString().slice(0,10)} onChange={event=>update("dateOfBirth",event.target.value)} required type="date" value={draft.dateOfBirth}/><span className="helper">Age is derived from the date of birth.</span></label><label>Sex<select disabled={busy} onChange={event=>update("sex",event.target.value as Draft["sex"])} value={draft.sex}><option value="NOT_SPECIFIED">Prefer not to say</option><option value="FEMALE">Female</option><option value="MALE">Male</option><option value="NON_BINARY">Non-binary</option></select></label><label>Specialization<input disabled={busy} onChange={event=>update("specialization",event.target.value)} required value={draft.specialization}/></label></div><button disabled={busy} type="submit">{busy?"Creating…":"Create Doctor"}</button></form>:null}{notice?<p className="feedback">{notice}</p>:null}{error?<p className="error">{error}</p>:null}{items===null?<p className="muted">Loading clinic-created doctors…</p>:items.length?<ul className="stack">{items.map(item=><li className="card" key={item.id}><div className="card-title"><strong>{item.displayName}</strong><span className="status-badge">Created by Clinic</span></div><span className="muted">{item.specialization}</span><p>Platform status: <span className="status-badge">{platformStatus(item.status)}</span></p><p>Professional verification: <span className="muted">Managed separately after approval</span></p>{item.status==="REJECTED"&&item.rejectionReason?<p className="error">Platform reason: {item.rejectionReason}</p>:null}</li>)}</ul>:<div className="empty-state"><strong>No clinic-created doctors</strong><p>Create a doctor here, or connect an independently registered doctor below.</p></div>}</section>;
}
